CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Usuario" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "Email" text NOT NULL,
    "Senha" text NOT NULL,
    CONSTRAINT "PK_Usuario" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240319102945_Criacao-Inicial', '8.0.3');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240322202023_CriacaoCadastroAtividade', '8.0.3');

COMMIT;

START TRANSACTION;

CREATE TABLE "CadAtividade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodAtividade" text NOT NULL,
    "Grupo" text NOT NULL,
    "CodigoFederal" text NOT NULL,
    "Descrição" text NOT NULL,
    "AtivPrevistaExcecao" text NOT NULL,
    "RetencaoObrigatoria" text NOT NULL,
    "Aliquota" real NOT NULL,
    CONSTRAINT "PK_CadAtividade" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240322202244_CriacaoCadastroAtividade01', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "CadAtividade" RENAME COLUMN "Descrição" TO "Descricao";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240323025622_CriacaoCadastroAtividadeUpdate02', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "CadAtividade" ADD "Recolhimento" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240324203326_AlterTableCadAtividade01', '8.0.3');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240324203740_AlterTableCadAtividade03', '8.0.3');

COMMIT;

START TRANSACTION;

DROP TABLE "CadAtividade";

CREATE TABLE "CadastroAtividade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodAtividade" text NOT NULL,
    "Grupo" text NOT NULL,
    "CodigoFederal" text NOT NULL,
    "Descricao" text NOT NULL,
    "AtivPrevistaExcecao" text NOT NULL,
    "RetencaoObrigatoria" text NOT NULL,
    "Aliquota" real NOT NULL,
    "Recolhimento" text NOT NULL,
    CONSTRAINT "PK_CadastroAtividade" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240324205612_RecreateCadAtividadeTable', '8.0.3');

COMMIT;

