// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoDev1.Models;

#nullable disable

namespace ProjetoDev01.Migrations
{
    [DbContext(typeof(BancoDados))]
    [Migration("20240324205612_RecreateCadAtividadeTable")]
    partial class RecreateCadAtividadeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoDev01.Models.CadastroAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("Aliquota")
                        .IsRequired()
                        .HasColumnType("real")
                        .HasColumnName("Aliquota");

                    b.Property<string>("AtivPrevistaExcecao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("AtivPrevistaExcecao");

                    b.Property<string>("CodAtividade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CodAtividade");

                    b.Property<string>("CodigoFederal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CodigoFederal");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descricao");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Grupo");

                    b.Property<string>("Recolhimento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Recolhimento");

                    b.Property<string>("RetencaoObrigatoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RetencaoObrigatoria");

                    b.HasKey("Id");

                    b.ToTable("CadastroAtividade");
                });

            modelBuilder.Entity("ProjetoDev1.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
